import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Toolbox } from "../components/ToolBox";
import { useLottie } from "lottie-react";
import devAnimation from "../../public/dev.json";
import workAnimation from "../../public/work.json";
import { HomeProjectBox } from "../components/HomeProjectBox";
import { Navbar } from "../components/Navbar";

const Home: NextPage = () => {
  const options = {
    animationData: devAnimation,
    loop: true,
  };

  const options2 = {
    animationData: workAnimation,
    loop: true,
  };

  const { View: dev } = useLottie(options);
  const { View: work } = useLottie(options2);

  return (
    <>
      <Head>
        <title>Temiloluwa Adeleye: Fullstack Engineer Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <style></style>
      </Head>
      <Navbar/>
      <main className="mx-auto flex  h-screen w-11/12 max-w-[90rem] flex-wrap items-center justify-between font-author">
        <section className="max-w-xl lg:max-w-lg">
          <h1 className="mb-4 text-5xl font-medium md:text-6xl">
            <span className="block">Hello.</span> I&apos;m Adeleye Temiloluwa.
          </h1>
          <h2 className="text-lg font-medium opacity-60 md:text-xl">
            I&apos;m a fullstack software engineer based in Abeokuta. I&apos;ve
            been writing web dev code and pushing HTML div tags for the past 15 months.
          </h2>
          <div className="mt-4 flex">
            <Link href="https://github.com/temiloluwa-js">
              <Image
                src="/github.svg"
                alt="Github Link"
                width={30}
                height={30}
                className="mr-4"
              />
            </Link>
            <Link href="https://twitter.com/_abdurrazaq_">
              <Image
                src="/twitter.svg"
                alt="Twitter Link"
                width={30}
                height={30}
              />
            </Link>
          </div>
        </section>
        <aside className="w-full lg:w-6/12">{dev}</aside>
      </main>
      <section className="mx-auto mb-8 w-11/12 max-w-[90rem]">
        <h1 className="mb-1 text-3xl  font-medium opacity-80 lg:text-4xl font-author">
          Technologies & Tools
        </h1>

      </section>
      <section className="mx-auto grid h-full w-11/12 max-w-[90rem] gap-4 lg:grid-cols-2 ">
        <Toolbox
          name="Core"
          description="The core technologies I utilise everyday + Typescript for type safety."
          imgLinks={["/html.svg", "/css.svg", "/javascript.svg", "/typescript.svg"]}
        />
        <Toolbox
          name="Frontend"
          description="The technologies I use when making frontend apps."
          imgLinks={["/reactjs.svg", "/tailwind.svg", "/nextjs.svg"]}
        />
        <Toolbox
          name="Backend"
          description="The technologies I use when dealing with projects that require server side logic."
          imgLinks={[
            "/nodejs.svg",
            "/trpc.svg",
            "/postgresql.svg",
            "/firebase.svg",
          ]}
        />
        <Toolbox
          name="Tools"
          description="Everyday tools that ease my development workflow."
          imgLinks={["/vscode.svg", "/git.svg", "/postman.svg"]}
        />
      </section>
      <section className="mt-12 flex flex-col  mx-auto w-11/12 max-w-[90rem] py-8 font-author">
      <h1 className="mb-1 text-3xl  font-medium opacity-80 lg:text-4xl font-author">
          Work
        </h1>

        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          <HomeProjectBox
            name="Shifuku Hotel"
            invert={false}
            textColor="black"
            headingColor="black"
            gitUrl="https://github.com/temiloluwa-js/shifuku-client"
            liveUrl="https://shifukuhotel.vercel.app"
            description="Shifuku Hotel is a full stack hotel application built with MongoDB, ExpressJS, ReactJS and NodeJS. Users can make bookings and admins can manage  bookings and rooms."
            imgUrl="/shifuku.png"
            color="white"
          />
          <HomeProjectBox
            name="66CH"
            textColor="white"
            invert={true}
            headingColor="white"
            gitUrl="https://github.com/temiloluwa-js/66ch-2"
            liveUrl="https://66ch.vercel.app"
            description="66ch is a blog built with React, Tailwind CSS and Firebase. Users can read blogs,  create blogs, search posts, comment, reply and a lot more things."
            imgUrl="/66ch.png"
            color="#0337F2"
          />
          <HomeProjectBox
            name="Misc Avatars"
            textColor="white"
            invert={true}
            headingColor="white"
            gitUrl="https://github.com/temiloluwa-js/misc"
            liveUrl="https://miscavatars.vercel.app"
            description="
            An ecommerce website where Dicebear Avatars are bought. Users can add and remove avatars from cart, switch between light and dark modes and pay for avatars using the Paypal Web SDK."
            imgUrl="/miscavatars.png"
            color="#1CA182"
          />
          <HomeProjectBox
            name="Leemao [WIP]"
            textColor="white"
            invert={true}
            gitUrl=""
            liveUrl="https://leemao-one.vercel.app"
            headingColor="#269CBE"
            description="Leemao is a website with a curation of African memes that can be downloaded or shared across all social media apps."
            imgUrl="/leemaologo.png"
            color="#16121A"
          />
        </div>
        <Link href="" className=" p-3 mt-6 transition-transform  hover:scale-110 rounded-md mx-auto bg-[#111] text-white text-lg">View All Projects</Link>
      </section>
      <section className="mx-auto pb-24  h-[80vh] w-11/12  max-w-[90rem] font-author lg:my-12">
        <h1 className="mt-20 mb-4 text-3xl  font-medium opacity-80 lg:mt-48 lg:text-5xl">
          Let&apos;s work together.
        </h1>
        <aside className="mt-8 w-full lg:mt-16 lg:w-3/12">{work}</aside>
        <p className="mt-8 underline underline-offset-1 text-xl font-medium opacity-70">Check out my resume.</p>
        <div className=" flex items-center justify-between lg:mt-56">
          <Link
            href="mailto:adeleyetemiloluwa674@gmail.com"
            className="flex h-32 w-32 items-center justify-center  border rounded-md bg-[#111] font-author text-xl font-medium uppercase text-white transition-transform  duration-300 hover:scale-110"
          >
            <span>Email me</span>
          </Link>
          <div className="flex">
            <Link href="https://github.com/temiloluwa-js">
              <Image
                src="/github.svg"
                alt="Github Link"
                width={30}
                height={30}
                className="mr-6"
              />
            </Link>
            <Link href="https://twitter.com/_abdurrazaq_">
              <Image
                src="/twitter.svg"
                alt="Twitter Link"
                width={30}
                height={30}
              />
            </Link>
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;
