import { type NextPage } from "next";
import Head from "next/head";
import * as LottiePlayer from "@lottiefiles/lottie-player";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex flex-wrap h-[90vh] w-11/12 max-w-[100rem] items-center justify-around font-author">
        <section className="max-w-lg">
          <h1 className="mb-4 md:text-6xl text-5xl font-medium">
            <span className="block">Hello.</span> I&apos;m Adeleye Temiloluwa.
          </h1>
          <h2 className="md:text-xl text-lg font-medium opacity-60">
            I&apos;m a fullstack software engineer based in Abeokuta and
            I&apos;ve been writing code and pushing html div tags for the past 15
            months.
          </h2>
          <div className="mt-4 flex">
            <Image src="/github.svg" alt="Github Link" width={30} height={30} className="mr-4"/>
            <Image src="/twitter.svg" alt="Twitter Link" width={30} height={30} />
          </div>
        </section>
        <aside className="md:w-6/12 w-full">
          <lottie-player
            src="https://assets9.lottiefiles.com/packages/lf20_nba42znq.json"
            background="transparent"
            speed="1"
            loop
            autoplay
          ></lottie-player>
        </aside>
      </main>
      <section className="max-w-[100rem] w-11/12">

      </section>
    </>
  );
};

export default Home;
